### ISSUE TITLE
Bad Request - Request Too Long

### ISSUE THREAD

**Issue by spottedmahn** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#10]
Upon signing into my tenant I'm receiving:

> Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long.

Attached is the full request: [Bad Request - Request Too Long.txt](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/files/1126084/Bad.Request.-.Request.Too.Long.txt)

The first few sign-ins worked.  I'm not sure what exactly changed to make it stop working.  Any thoughts?

**Comment by parakhj** [comment]
Each time you sign in, it's storing more cookies in your browser. Since the domain is the same, the browser sends all of the cookies, including the stale ones. This is blowing up the cookie header fields and making the headers too long. To fix it, just clear your cookies. If you're testing your setup, I would recommend using a private browser.

**Comment by RobARichardson** [comment]
My organization and our clients are regularly seeing this issue.  We use Azure AD w/ the Office 365 Suite of apps, Visual Studio Team Services, Azure Portal, and an Azure AD B2C instance.  When using all of these applications at once in a browser, we encounter this error regularly. Clearing cookies is okay once in a while but gets annoying quickly.  Furthermore, we can't also expect our customer who are using Azure AD B2C and other MSFT services to be expected to do the same.  Is there anything we can do on our end to resolve this problem so we don't have to tell our customers to clear their cookies or use a private/incognito browser session.

**Comment by spottedmahn** [comment]
@RobARichardson I don't know if you'll get much traction on this thread...

FYI, I just hit this error today using portal.azure.com.  [I posted it to SO](https://stackoverflow.com/questions/46100272/azure-portal-bad-request-request-too-long).  Hopefully, some more insights will come out of it.

When I got the error originally, I figured I need to do more work in my app to prevent this.  But today, I received it using the Azure portal.  And based upon your desc, maybe there's a more fundamental problem here.  Not sure.

**Comment by gsacavdm** [comment]
@RobARichardson , @spottedmahn , I replied to the StackOverflow post. Nothing to useful unfortunately given that there isn't a great answer today.

Summary:
* Long term answer is [custom domains](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/15334317-customer-owned-domains), that's in the works, vote for it.
* In the interim, clear cookies (lame, yes)
* Alternatively, see if you can try reducing the [number of claims included in the token](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-reference-custom-attr#use-a-custom-attribute-in-your-sign-up-policy) (sometimes helps).

**Comment by ElvisLives** [comment]
@parakhj @gsacavdm 

- Voted for custom domains.  (An eta would be nice on this.)
- Clearing cookies is an unrealistic solution for a normal user.  Should we tell our users to log in incognito to access our apps?  (**How could this issue be closed when it is a production issue that doesn't just affect devs/engineers?**)
- The number of claims we have is almost the bare minimum.  (Less than 7 total with one custom claim.)

**Comment by gsacavdm** [comment]
Totally understand where you guys are coming from. Clearing the cookies is meant for the scenario where it happens to devs, which has been the majority of the reported cases so far. But again, no argument that clearing cookies is (to put it mildly) an undesirable experience for end users. 

I believe (I'll let @parakhj chime in on this as I'm not on the B2C team anymore) that custom domains is one of the top priority items in the team's backlog, at which point this will be a nonissue. He should be able to provide a better ETA here (hopefully via an update to the feedback item).

As for the issue being closed, that's because this isn't an issue with the sample itself, but a limitation of B2C itself which is being tracked via that outstanding feedback entry.

**Comment by parakhj** [comment]
Agreed with @gsacavdm above. Custom domains (the ability for you to choose your domain) is hitting a few technical issues, so we are working to enable a new domain that B2C tenants can run on (something like b2clogin.com). This will be shipped earlier than custom domains, so that you won't see the cookies issues that you are noticing on login.microsoftonline.com. I would vote [this feature](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/15493536-add-support-for-javascript-inside-the-custom-ui-br) so that you know when we enable the preview for it.

**Comment by ElvisLives** [comment]
@parakhj @gsacavdm  Thanks guys for the quick responses.  Makes sense why it's closed for this sample.  Cheers.

**Comment by hetalmadhani** [comment]
> Agreed with @gsacavdm above. Custom domains (the ability for you to choose your domain) is hitting a few technical issues, so we are working to enable a new domain that B2C tenants can run on (something like b2clogin.com). This will be shipped earlier than custom domains, so that you won't see the cookies issues that you are noticing on login.microsoftonline.com. I would vote [this feature](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/15493536-add-support-for-javascript-inside-the-custom-ui-br) so that you know when we enable the preview for it.

The feature requested to vote on is from enabling javascript for custom login page, is there a separate feature request for a new domain like b2clogin?

**Comment by chrift** [comment]
We have moved over to using the b2clogin.com domain, but we are still getting this issue.

I don't think it's right that this issue be closed.

**Comment by junioredmar** [comment]
This is the name of the cookie being stored: "x-ms-cpim-rc" 
Which as per MS Documentation is "Used for storing the relay cookie."
Is there a way for disabling it, or if we can force the deletion of the old ones?

**Comment by markarnolditpro** [comment]
This is a problem for my organization as well.  We went through a lot of hoops to get B2C as a solution and having no clear solution to this isn't going over well with the stakeholders.    We are already using the b2clogin.com domain.  Any guidance on clearing the offending cookies programmatically or otherwise would help.

**Comment by imercerwillow** [comment]
This issue should be reopened. The suggested feature request link is broken, the problem still persists. Our customers are hitting this. I have *94* `x-cpim-...` cookies in my request and I cleared them yesterday.

**Comment by sam2332** [comment]
Can we get some movement on fixing the failing state of azure demos?

**Comment by Sipower** [comment]
> This issue should be reopened. The suggested feature request link is broken, the problem still persists. Our customers are hitting this. I have _94_ `x-cpim-...` cookies in my request and I cleared them yesterday.

Are you experiencing this issue in dev environment or in live production?

**Comment by imercerwillow** [comment]
@Sipower In production. We have multiple websites using the same b2c which appears to amplify the problem, and it doesn't take long to run up a huge set of `x-ms-cpim-rc:...` cookies which eventually breaks login. Our customers only use one or two sites with the same B2C settings but they also hit this problem from time to time.

**Comment by gsacavdm** [comment]
I no longer work at the Azure AD B2C team nor Microsoft, but FYI for others interested on this thread, the feature I reference a loooong time ago - [custom domains](https://feedback.azure.com/d365community/idea/506561f5-b825-ec11-b6e6-000d3a4f0789) is now available. That should help with this issue.

**Comment by imercerwillow** [comment]
@gsacavdm  It doesn't help [much]. We are using a custom domain and still hit this issue regularly.

**Comment by gsacavdm** [comment]
Ah, sorry about that  :S

I'm not sure what B2C is stashing in the cookies these days that results in this error when you have an isolated domain. I'll defer to the Microsoft team to provide more insights.

**Comment by jayallen** [comment]
Just an FYI: I work on B2C team and our people are looking at this issue (not for the first time, I'll note--we've fixed this in the past).  We'll report back as soon as we have more information.

**Comment by imercerwillow** [comment]
@jayallen Any update? Can we get this bug re-opened at least?

**Comment by kurtwaldowski-echelon** [comment]
@jayallen @DannyJHM @imercerwillow Just happened again to a user in production today >.< hoping for a resolution soon

**Comment by jparikh12** [comment]
@jayallen, this is happening to us as well. The long cookie header search on google is how I came across this as well. It started happening after we implemented the custom domain with B2C and Azure Front Door. 

Is there any update?

**Comment by ChristopheBeke** [comment]
Issue is still occurring. If there is a fix, please let me know!

**Comment by xosevilla** [comment]
Same for me, Issue is still occurring.

**Comment by corbin-infonetica** [comment]
Weve started to encounter this issue today, google bought me here
