### ISSUE TITLE
Caching issuer and keys from the metadata endpoint

### ISSUE THREAD

**Issue by salvatore-garrubba** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#38]
Hello all,

I've implemented the _OpenIdConnectCachingSecurityTokenProvider_  but I'm wondering why all the time we need to make a call to retrieve the keys and the issuer from the metadata endpoint:

https://login.microsoftonline.com/{TENANT}.onmicrosoft.com/v2.0/.well-known/openid-configuration?p={POLICY}

As far as I know, the keys contains the public key that never changes and the issuer is always the same.

The only reason for get all the time the fresh value is that we change the B2C policy, right?

So, can we cache these values?

**Comment by mkarpuk** [comment]
The overall implementation of the `OpenIdConnectCachingSecurityTokenProvider` looks suspicious to me. It uses `ReaderWriterLockSlim`, but acquires WRITE lock on each request to the property which does not look like the right way to use locks. I would say that this class should be corrected to properly use locks and actually do the caching

**Comment by ggirard07** [comment]
@salvatore-garrubba Microsoft is rotating the keys periodically. That's why [they advise in their docs](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-tokens#validate-the-signature) to refresh those every 24h.

> Azure AD rotates the possible set of keys periodically, so your app should be written to handle those key changes automatically. A reasonable frequency to check for updates to the public keys used by Azure AD is every 24 hours.

If you look at the actual implementation of [`ConfigurationManager.GetConfigurationAsync`](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L177) is cached by default for 24h. You can confirm that behavior with FIddler and see that the configuration is fetched only once.
