### ISSUE TITLE
Error reading to do list: Null user was passed in AcquiretokenSilent API. Pass in a user object or call acquireToken authenticate.

### ISSUE THREAD

**Issue by spottedmahn** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#9]
I've gotten my the web app and my ad tenant working so that I'm able to sign-in/create users.

I've verified this by reviewing my claims:

![image](https://user-images.githubusercontent.com/14079228/27881127-8a0f40fa-6195-11e7-83dc-785e7b5ed13a.png)

Now I'm trying to get the api going.  When I visit the tasks view I get:

> Error reading to do list: Null user was passed in AcquiretokenSilent API. Pass in a user object or call acquireToken authenticate.

I see that user is null and it shouldn't be based upon the error message I received.  What am I doing wrong?

![image](https://user-images.githubusercontent.com/14079228/27881475-bd8c8504-6196-11e7-991b-a311661a1fd3.png)

**Comment by spottedmahn** [comment]
I've noticed that if I go through the **entire sign-in** progress `user` will not be NULL.

`user` will only be NULL when I restart the app.  When I the browser opens, it see's me as signed in but apparently that's not enough.

### Repro Steps

1. Startup WebApp from VS
1. Sign-in to the app
1. Verify `user` is not null (by going to the task list)
1. Stop the app in VS
1. Start the app backup in VS
1. Verify the UI say's you are **still** signed in
1. Try to go to the task list and `user` will be NULL

**Comment by parakhj** [comment]
I believe that is due to the "dumbness" of the sample - the MSAL session cache is stored in memory. When you kill the app, it loses the cache. But since the cookie remains stored in your browser, when you start the app again and browse to the site, the cookie which contains a valid token authenticates you in, but then you can't get further since the cache is gone.

**Comment by Magrangs** [comment]
So is there a proposed solution to this?

**Comment by snobu** [comment]
Two years too late to the game but this thread still comes up at the top if you search for the exception message. This may help.

Instead of [doing this][1] (throwing a more specific exception), you could try around `AcquireTokenAsync` and catch `MsalUiRequiredException`. Then check if its `ErrorCode` field == `"user_null"` (signaling the cache problem) and simply redirect the user to the Sign-in flow by calling `Challenge()`.

This results in a login prompt rather than dealing with another exception. In most cases that's what you want.

```csharp
try
{
    result = await cca.AcquireTokenSilentAsync(
        scope,
        accounts.FirstOrDefault(),
        _azureAdB2COptions.Authority,
        false);
}
// https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/exceptions
catch (MsalUiRequiredException ex)
{
    // ex.ErrorCode != MsalUiRequiredException.UserNullError indicates a cache problem.
    // When calling an [Authenticate]-decorated controller we expect an authenticated
    // user and therefore its account should be in the cache. However in the case of an
    // InMemoryCache, the cache could be empty if the server was restarted. This is why
    // the null_user exception is thrown.

    Debug.WriteLine("MsalUiRequiredException thrown --\n" +
        $"  -- Type: {ex.GetType()}\n" +
        $"  -- ErrorCode: {ex.ErrorCode}");

    if (ex.ErrorCode == MsalUiRequiredException.UserNullError)
    {
        return Challenge(
            new AuthenticationProperties { RedirectUri = redirectUrl },
            OpenIdConnectDefaults.AuthenticationScheme);
    }
    else
    {
        // not a null_user in cache problem, handle accordingly
    }
}
```

You can find a basic implementation [**here (cachefix branch)**][2] and a better one using exception filter attributes and cleaner and more structured code, [**here (refactor branch)**][3] (all credit to @bojanv).

Many thanks to @jmprieur for [**this sample**][4] that had this pattern in first and is well-commented.
 
[1]: https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/pull/11/files
[2]: https://github.com/snobu/active-directory-aspnetcore-webapp-openidconnect-v2/blob/aec4844c2e8e5766d81870a953a6119fe81cdf4e/Controllers/HomeController.cs#L41-L83
[3]: https://github.com/snobu/active-directory-aspnetcore-webapp-openidconnect-v2/blob/refactor/Controllers/HomeController.cs#L35-L44
[4]: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2

**Comment by giwleb** [comment]
Curious if there's resources on a "less dumb" solution? What are the options other than "MSAL session cache is stored in memory"

**Comment by TiagoBrenck** [comment]
@giwleb a new version of this sample will be merged soon (1 or 2 days) and it has more documentation about this simple sample. 

About the cache storage options, usually developers decide to store it on a database. Take a look [on this SQL Cache helper classes](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web/Client/TokenCacheProviders/Sql), for a better reference.

Let us know if you need more help. Thanks
